namespace NewProject
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.htmlEditor1 = new SpiceLogic.WinHTMLEditor.HTMLEditor();
            this.panelControl1 = new DevExpress.XtraEditors.PanelControl();
            this.simpleButton1 = new DevExpress.XtraEditors.SimpleButton();
            ((System.ComponentModel.ISupportInitialize)(this.htmlEditor1)).BeginInit();
            this.htmlEditor1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.panelControl1)).BeginInit();
            this.panelControl1.SuspendLayout();
            this.SuspendLayout();
            // 
            // htmlEditor1
            // 
            this.htmlEditor1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.htmlEditor1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.htmlEditor1.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.htmlEditor1.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.htmlEditor1.BackgroundImagePath = "";
            this.htmlEditor1.BaseUrl = "";
            this.htmlEditor1.BodyColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.htmlEditor1.BodyHtml = null;
            this.htmlEditor1.BodyStyle = null;
            this.htmlEditor1.Charset = "unicode";
            this.htmlEditor1.Cursor = System.Windows.Forms.Cursors.Default;
            this.htmlEditor1.DefaultForeColor = System.Drawing.Color.Black;
            this.htmlEditor1.DocumentHtml = resources.GetString("htmlEditor1.DocumentHtml");
            this.htmlEditor1.DocumentTitle = "";
            this.htmlEditor1.EditorContextMenuStrip = null;
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_New", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "New", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "New", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Open", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Open", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems1"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Open", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Save", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Save", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems2"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Save", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(26, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator1", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, null, null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Font Name", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Font Name", null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Verdana", 8F), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(160, 24)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Font Size", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Font Size", null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator2", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, null, null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Cut", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Cut", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems3"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Cut", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(26, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Copy", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Copy", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems4"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Copy", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(27, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Paste", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Paste", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems5"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Paste", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(27, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator3", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, null, null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Bold", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Bold", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems6"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Bold", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Italic", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Italic", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems7"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Italic", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Underline", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Underline", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems8"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Underline", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Horizontal Rule", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Horizontal Rule", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems9"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Horizontal Rule", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Format Reset", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Format Reset", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems10"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Format Reset", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(34, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Undo", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Undo", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems11"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Undo", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Redo", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Redo", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems12"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Redo", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Edit Source", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Edit Source", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems13"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Edit Source", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(34, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Spell Check", SpiceLogic.WinHTMLEditor.ToolStripHosts.TopStrip, true, true, true, true, "Spell Check", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems14"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Spell Check", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Title Insert", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Title Insert", null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(105, 29)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Text Highlight Color", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Text Highlight Color", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems15"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Text Highlight Color", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Font Color", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Font Color", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems16"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Font Color", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator4", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, null, null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_HyperLink", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "HyperLink", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems17"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "HyperLink", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Image", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Image", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems18"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Image", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator5", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, null, null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Insert Ordered List", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Insert Ordered List", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems19"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Insert Ordered List", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Insert Unordered List", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Insert Unordered List", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems20"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Insert Unordered List", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator6", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, null, null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Left", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Left", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems21"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Left", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(26, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Center", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Center", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems22"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Center", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(26, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Right", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Right", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems23"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Right", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(26, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator7", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, null, null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Table", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Table", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems24"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Table", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator8", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, null, null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Outdent", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Outdent", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems25"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Outdent", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Indent", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Indent", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems26"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Indent", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Separator9", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, null, null, System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.None, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.SizeToFit, System.Drawing.Color.Empty, System.Windows.Forms.RightToLeft.No, null, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(0, 0)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Strike through", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Strike through", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems27"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Strike through", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(24, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_SuperScript", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "SuperScript", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems28"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "SuperScript", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(27, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Subscript", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Subscript", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems29"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Subscript", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(27, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Body Style", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Body Style", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems30"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Body Style", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(34, 26)));
            this.htmlEditor1.FactoryToolbarItems.Add(new SpiceLogic.WinHTMLEditor.FactoryItem("FACTORY_Print", SpiceLogic.WinHTMLEditor.ToolStripHosts.BottomStrip, true, true, true, true, "Print", ((System.Drawing.Image)(resources.GetObject("htmlEditor1.FactoryToolbarItems31"))), System.Drawing.Color.Empty, null, System.Windows.Forms.ImageLayout.None, System.Windows.Forms.ToolStripItemDisplayStyle.Image, new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0))), System.Drawing.Color.Black, System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripItemImageScaling.None, System.Drawing.Color.Magenta, System.Windows.Forms.RightToLeft.No, "Print", System.Drawing.ContentAlignment.MiddleCenter, System.Windows.Forms.ToolStripTextDirection.Horizontal, System.Windows.Forms.TextImageRelation.ImageBeforeText, System.Windows.Forms.ToolStripItemAlignment.Left, new System.Drawing.Size(23, 26)));
            this.htmlEditor1.Location = new System.Drawing.Point(233, 59);
            this.htmlEditor1.Name = "htmlEditor1";
            this.htmlEditor1.ScrollBars = SpiceLogic.WinHTMLEditor.ScrollBarVisibility.Default;
            this.htmlEditor1.Size = new System.Drawing.Size(833, 223);
            // 
            // 
            // 
            this.htmlEditor1.SpellCheckDictionary.DictionaryFile = "en-US.dic";
            // 
            // 
            // 
            this.htmlEditor1.SpellChecker.Dictionary = this.htmlEditor1.SpellCheckDictionary;
            this.htmlEditor1.TabIndex = 0;
            // 
            // htmlEditor1.HtmlEditorToolbar1
            // 
            this.htmlEditor1.Toolbar1.Location = new System.Drawing.Point(0, 0);
            this.htmlEditor1.Toolbar1.Name = "HtmlEditorToolbar1";
            this.htmlEditor1.Toolbar1.Size = new System.Drawing.Size(833, 27);
            this.htmlEditor1.Toolbar1.TabIndex = 0;
            this.htmlEditor1.Toolbar1.Text = "toolStrip1";
            // 
            // htmlEditor1.HtmlEditorToolbar2
            // 
            this.htmlEditor1.Toolbar2.Location = new System.Drawing.Point(0, 27);
            this.htmlEditor1.Toolbar2.Name = "HtmlEditorToolbar2";
            this.htmlEditor1.Toolbar2.Size = new System.Drawing.Size(833, 29);
            this.htmlEditor1.Toolbar2.TabIndex = 1;
            this.htmlEditor1.Toolbar2.Text = "toolStrip2";
            this.htmlEditor1.ToolbarContextMenuStrip = null;
            this.htmlEditor1.ToolbarCursor = System.Windows.Forms.Cursors.Default;
            // 
            // panelControl1
            // 
            this.panelControl1.Controls.Add(this.htmlEditor1);
            this.panelControl1.Controls.Add(this.simpleButton1);
            this.panelControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelControl1.Location = new System.Drawing.Point(0, 0);
            this.panelControl1.Name = "panelControl1";
            this.panelControl1.Size = new System.Drawing.Size(1016, 351);
            this.panelControl1.TabIndex = 1;
            // 
            // simpleButton1
            // 
            this.simpleButton1.Location = new System.Drawing.Point(420, 30);
            this.simpleButton1.Name = "simpleButton1";
            this.simpleButton1.Size = new System.Drawing.Size(75, 23);
            this.simpleButton1.TabIndex = 0;
            this.simpleButton1.Text = "GetText";
            this.simpleButton1.Click += new System.EventHandler(this.simpleButton1_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1016, 351);
            this.Controls.Add(this.panelControl1);
            this.Name = "Form1";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.htmlEditor1)).EndInit();
            this.htmlEditor1.ResumeLayout(false);
            this.htmlEditor1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.panelControl1)).EndInit();
            this.panelControl1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private SpiceLogic.WinHTMLEditor.HTMLEditor htmlEditor1;
        private DevExpress.XtraEditors.PanelControl panelControl1;
        private DevExpress.XtraEditors.SimpleButton simpleButton1;
    }
}

